name: development
on:
  pull_request:
    branches:
      - development
    types: [closed]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  documentation:
    if: github.event.pull_request.merged == true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'page'
          token: ${{ secrets.SYNC_TOKEN }}
      - name: Create and push documentation
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@github.com

          git config pull.rebase true
          git pull origin development

          pip3 install mkdocs

          cd mkdocs;
          for val in $(mkdocs get-deps); do pip3 install $val; done
          cd ..

          npm run buildDocs latest

          git add mkdocs docs
          git commit -m "Update documentation page"
          git push --force
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
